#1353 & #1354 refactor: idea handler & idea card
knoffhoff/hms pull request #1356
Opened 2023-04-25 11:05 UTC by rz-p

2023-04-25 15:17 UTC, rz-p commented
Conditionals  are **NOT** working yet, but the cards are technically functional (CRUD works). 

Not sure what to do with `IdeaDetails` as it is pretty much the same as `IdeaCard`

2023-04-28 05:49 UTC, LetsPoke commented on hms-app/src/components/card-details/IdeaDetails.tsx
> +  const ideaName = () => {
maybe ideaHeader would be a better name as it contains the owner pictue, name and idea title

2023-04-28 05:52 UTC, LetsPoke commented on hms-app/src/components/card-details/IdeaDetails.tsx
> +  const ideaSkills = ()  => {
this const feels unnessasary 
you could replace the "div" in required skills const with "card.section" and would save some lines of code

2023-04-28 05:56 UTC, LetsPoke requested changes
1. in the ideation portal im able to see all buttons that only the idea owner should be able to see
2. in the hackathon page I cant see any ideas
3. can you show me your prettier settings? look like we have different ones

2023-04-28 06:07 UTC, LetsPoke commented on hms-app/src/components/card-details/IdeaDetails.tsx
> +    // __DO NOT DELETE FOR NOW (MINIMAL CARD)__
why should we merge it with outcommented code?

2023-05-09 13:27 UTC, reyhanrumengan approved these changes

2023-05-09 13:47 UTC, LetsPoke approved these changes

2023-05-09 13:50 UTC, merged